apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoibWthcGFsa2Etc2ljcGEiLCJwYXNzd29yZCI6ImdocF9aeTExVUxNSzhSWU83eGlycWhycE9KNXBkUXFlUzEyeUxVbzAiLCJhdXRoIjoiYld0aGNHRnNhMkV0YzJsamNHRTZaMmh3WDFwNU1URlZURTFMT0ZKWlR6ZDRhWEp4YUhKd1QwbzFjR1JSY1dWVE1USjVURlZ2TUE9PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: ghcr-sicpa-foundations
type: kubernetes.io/dockerconfigjson
